NUMBER_OF_KUBERNETES_NODES = 2

Vagrant.configure("2") do |config|
    config.ssh.insert_key = false

    config.vm.provider "virtualbox" do |v|
        v.memory = 1024
        v.cpus = 2
    end
      
    config.vm.define "k8s-master" do |master|
        master.vm.box = "ubuntu/bionic64"
        master.vm.box_version = "20200610.1.0"
        master.vm.network "private_network", ip: "192.168.50.10"
        master.vm.hostname = "k8s-master"
        master.vm.provision "ansible" do |ansible|
            ansible.playbook = "master-playbook.yml"
            ansible.extra_vars = {
                node_ip: "192.168.50.10",
            }
        end
    end

    (1..NUMBER_OF_KUBERNETES_NODES).each do |i|
        config.vm.define "node-#{i}" do |node|
            node.vm.box = "ubuntu/bionic64"
            node.vm.box_version = "20200610.1.0"
            node.vm.network "private_network", ip: "192.168.50.#{i + 10}"
            node.vm.hostname = "node-#{i}"
            node.vm.provision "ansible" do |ansible|
                ansible.playbook = "node-playbook.yml"
                ansible.extra_vars = {
                    node_ip: "192.168.50.#{i + 10}",
                    node_index: "#{i}",
                }
            end
        end
    end
end
