version: "3.7"

services:

    jenkins:

        image: devops4me/jenkins-2.0
        container_name: vm.jenkins-2.0
        network_mode: host
        restart: unless-stopped

        volumes:
            # enable Jenkins to use the docker daemon from the host
            - /var/run/docker.sock:/var/run/docker.sock
            - /usr/bin/docker:/usr/bin/docker

    sonar-database:

        image: postgres:11.2
        container_name: vm.sonardb
        network_mode: host
        restart: unless-stopped

        environment:
            - POSTGRES_USER=sonar_rw_xyz123abc
            - POSTGRES_PASSWORD=xyzP23FSsd8ffa8So2bJw4so
            - POSTGRES_DB=sonar_db_hyqlbi

    sonarqube:

        image: sonarqube:7.7-community
        container_name: vm.sonarqube
        network_mode: host
        restart: unless-stopped

        depends_on:
            - sonar-database
            - fluentd
            - elasticsearch

        environment:
            - sonar.jdbc.username=sonar_rw_xyz123abc
            - sonar.jdbc.password=xyzP23FSsd8ffa8So2bJw4so
            - sonar.jdbc.url=jdbc:postgresql://localhost/sonar_db_hyqlbi

        logging:
            driver: "fluentd"
            options:
                fluentd-address: localhost:24224
                tag: vm.sonarqube

    docker-registry:

        image: registry
        container_name: vm.registry
        network_mode: host
        restart: unless-stopped

    nexus-repository:

        image: sonatype/nexus3
        container_name: vm.nexus
        network_mode: host
        restart: unless-stopped

    fluentd:
        build: ./fluentd
        container_name: vm.fluentd
##        network_mode: host

        depends_on:
            - elasticsearch

        volumes:
            - ./fluentd:/fluentd/etc

        ports:
            - "24224:24224"
            - "24224:24224/udp"

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.3.0
        container_name: vm.elasticsearch
        network_mode: host
        expose:
            - 9200

    kibana:
        image: docker.elastic.co/kibana/kibana-oss:6.3.0
        container_name: vm.kibana
        network_mode: host

        depends_on:
            - elasticsearch
