apiVersion: v1
kind: Pod
metadata:
    name: pod.wiki
    labels:
        pod-type: wiki
spec:
    containers:
    - name: vmwiki
      image: "devops4me/wiki"
      env:
      - name: WIKI_CONTENT_REPO_URL
        value: "https://github.com/apolloakora/devops-wiki"
      ports:
      - containerPort: 4567
