apiVersion: apps/v1
kind: Deployment
metadata:
    name: jenkins
spec:
    replicas: 3
    selector:
        matchLabels:
            pod-type: jenkins
    template:
        metadata:
            name: jenkins
            labels:
                pod-type: jenkins
        spec:
            containers:
            -   name: vm-jenkins
                image: devops4me/jenkins-2.0
                env:
                -   name: WIKI_CONTENT_REPO_URL
                    value: "https://github.com/apolloakora/devops-wiki"
                ports:
                -   containerPort: 8080
