apiVersion: apps/v1
kind: Deployment
metadata:
    name: wiki
spec:
    replicas: 3
    selector:
        matchLabels:
            pod-type: wiki
    template:
        metadata:
            name: wiki
            labels:
                pod-type: wiki
        spec:
            containers:
            -   name: vm-wiki
                image: devops4me/wiki:latest
                env:
                -   name: WIKI_CONTENT_REPO_URL
                    value: "https://github.com/apolloakora/devops-wiki"
                ports:
                -   containerPort: 4567
---
apiVersion: v1
kind: Service
metadata:
    name: wiki
spec:
    ports:
    - port: 80
      targetPort: 4567
    selector:
        pod-type: wiki
