version: '3'

services:

    webserver:
        build: .
        container_name: vm.web.flask
        ports:
            - "5000:5000"

    redis:
        image: "redis:alpine"
        container_name: vm.web.redis
